### ISSUE TITLE
Work on Job Listing using Vuejs

### ISSUE THREAD

**Issue by Timtech4u** [Timtech4u/employee-manager#1]
Need to work on Job listings based on the /jobs/ endpoint.

**Comment by mathagician** [comment]
Hello @Timtech4u, I would like to work upon this issue, Can u please describe in detail about the issue.

**Comment by Timtech4u** [comment]
Hi @mathagician , this is an open employee manager portal, we make use of Django admin for managing employees.

However we want a front end for displaying jobs, we have documented API for jobs here: http://saidu.myemp.site/docs/#jobs-list

We're using Vuejs for the frontend.

**Comment by jatempa** [comment]
I want to work on this !

**Comment by jatempa** [comment]
I have a trouble with the installation process. Please @Timtech4u  can you send me an instructions file to setup?

**Comment by Timtech4u** [comment]
Hi @jatempa , you'll need to dependencies installed, you need to run the following commands:

`pip install -r requirements.txt`
`npm install`

Note that the project uses Python3 and Vuejs.
Kindly share any error you get with me.
